# Generated by Django 4.1.2 on 2022-12-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belajar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managemen',
            old_name='Organisasi',
            new_name='organisasi',
        ),
    ]
